version: '3.7'
    
services:
  db:
    #image: postgres:12.4
    image: timescale/timescaledb:latest-pg12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db/postgresql:/var/lib/postgresql/data
      #- ./dump:/dump
  stats:
    build:
      context: ./back
      target: dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back:/app
    ports:
      - "8000:8000"
      - "3500:3500"
    depends_on:
      - db
  front:
    build: 
      context: ./front
      target: dev
    command: npm start
    volumes:
      - ./front:/app
      - /app/node_modules
    ports: 
      - "3000:3000"

  # The Redis image will run on the sandbox network

networks:
  default:
      external:
          name: sandbox_default
    