# Generated by Django 2.2.16 on 2021-08-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='block_id',
        ),
        migrations.AddField(
            model_name='video',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='end',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='segment',
            name='start',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='watch_time',
            field=models.FloatField(),
        ),
    ]
