# Generated by Django 2.2.16 on 2021-08-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0002_auto_20210823_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='is_active',
        ),
    ]
