# Generated by Django 2.2.16 on 2021-08-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0003_remove_video_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='end',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='segment',
            name='start',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='watch_time',
            field=models.IntegerField(),
        ),
    ]
