# Generated by Django 2.2.16 on 2021-09-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0004_auto_20210827_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewonvideo',
            name='coverage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
