# Generated by Django 2.2.16 on 2020-10-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitOnPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type_vertical', models.TextField()),
                ('sequential', models.TextField(blank=True)),
                ('course', models.TextField()),
                ('username', models.CharField(max_length=150)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
