# Generated by Django 2.2.16 on 2020-10-30 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitonpage',
            old_name='event_type_vertical',
            new_name='vertical',
        ),
        migrations.AddField(
            model_name='visitonpage',
            name='chapter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitonpage',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
