# Generated by Django 2.2.16 on 2021-08-11 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_auto_20201030_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitonpage',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='visitonpage',
            name='course',
        ),
        migrations.RemoveField(
            model_name='visitonpage',
            name='sequential',
        ),
        migrations.AlterField(
            model_name='visitonpage',
            name='vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CourseVertical'),
        ),
    ]
