# Generated by Django 2.2.16 on 2022-01-10 18:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_student_last_update'),
        ('visits', '0003_auto_20210811_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionOnBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('completion', models.IntegerField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CourseVertical')),
            ],
        ),
    ]
