AWS_ACCESS_KEY_ID: acs98jmdf98ansxdf89asxf
AWS_SECRET_ACCESS_KEY: asiodfcnasd98fcuas8fcunadsf9c8asdfcasdoifxm89sdfx9a8
AWS_STORAGE_BUCKET_NAME: bucket
AWS_DEFAULT_ACL: 'public-read'
AWS_S3_REGION_NAME: ''
AWS_S3_ENDPOINT_URL: 'http://minio:9000'
ALLOWED_HOSTS:
  - '*'
BACKEND_SERVICE_EDX_OAUTH2_KEY: 'DDcGnr6ToTppIOVFg5j6FCqAMLMzHTCpgZJieBZz'
BACKEND_SERVICE_EDX_OAUTH2_SECRET:  '5SLNfuafLp2ld1FI3flFewQeEeFw9QDS8QL4MtNtHm8uXVZxa4jyjIQbud18oAD1sLxhmn99cA3h0LlD3OBckab8fValGIJqxZxdrivey0rCA7EW6XByaIwYr3IbuXam'  # Local Development Values
BACKEND_SERVICE_EDX_OAUTH2_PROVIDER_URL: 'https://local-eol.uchile.cl/oauth2'
BACKEND_LMS_BASE_URL: 'https://local-eol.uchile.cl'
BACKEND_CMS_BASE_URL: 'https://studio.local-eol.uchile.cl' # CORRECT
BACKEND_ALLOWED_ROLES:
  - 'staff'
  - 'data researcher'
  - 'instructor'
  - 'administrator'
BACKEND_LOGS_DIR: '/app/logs'
CACHE:
  default:
    BACKEND: 'django_redis.cache.RedisCache'
    LOCATION: 'redis://@redis:6380/3'
    OPTIONS:
      CLIENT_CLASS: 'django_redis.client.DefaultClient'
      PASSWORD: 'msecret318e401514dd45e97daf49d1d5c36cdbf9a7294395e84a9f52c08c6ad3699fcc0'
    KEY_PREFIX: 'stats'
CELERY_BROKER_URL: 'redis://msecret318e401514dd45e97daf49d1d5c36cdbf9a7294395e84a9f52c08c6ad3699fcc0@redis:6380/2'
CELERY_BACKEND: 'redis://msecret318e401514dd45e97daf49d1d5c36cdbf9a7294395e84a9f52c08c6ad3699fcc0@redis:6380/2'
DJANGO_SECRET_KEY: 'lif-s82+7##n-lma+v@l_suzftkxy0%o&-ohnt6^^g_t9fu1bx'
DATABASES:
  default:
    ENGINE: 'django.db.backends.postgresql'
    NAME: 'postgres'
    USER: 'postgres'
    PASSWORD: 'postgres'
    HOST: 'db'
    PORT: 5432
EDX_DRF_EXTENSIONS:
  OAUTH2_USER_INFO_URL: "https://local-eol.uchile.cl/oauth2/user_info"
JWT_AUTH: 
  JWT_ALGORITHM: HS256
  JWT_AUTH_COOKIE_HEADER_PAYLOAD: edx-jwt-cookie-header-payload
  JWT_AUTH_COOKIE_SIGNATURE: edx-jwt-cookie-signature
  JWT_AUTH_HEADER_PREFIX: 'JWT' # distinto
  JWT_AUTH_REFRESH_COOKIE: edx-jwt-refresh-cookie
  JWT_AUTH_COOKIE: 'edx-jwt-cookie' # distinto
  JWT_DECODE_HANDLER: 'edx_rest_framework_extensions.auth.jwt.decoder.jwt_decode_handler' # distinto
  JWT_VERIFY_AUDIENCE: False # distinto
  
  JWT_AUDIENCE: https://local-eol.uchile.cl
  JWT_ISSUER: https://local-eol.uchile.cl
  JWT_ISSUERS:
    - AUDIENCE: https://local-eol.uchile.cl
      ISSUER: https://local-eol.uchile.cl
      SECRET_KEY: 'jwt_secret'
  JWT_PRIVATE_SIGNING_JWK: '{"kty": "RSA", "kid": "FEE4CI2B", "n": "6dmKES5VIa8BGU3CEpFU2qpd93jz5VySP2gTYmtjvpwP1TzrlzD2mys4Ia5b7WLSsZuhC0iPYD1oXclvYWW56qB-1rzAIXnqZo0q_9UB0cfxJzQknVK5AWA3Iu5hQLzEw4xPG46054KxiBIZaIhIVbl_HHMk1wVRy-v-3iRWN2yP-4nhsz9jRHAMqIaQTApXUFXTct3AZRbHBBffi9yJdIOYpp606HIMvbTCq6IzEi_WOFm7gCb1a3X4LtjagXFvASGfCiRjw7ZFBY5e9lEgoKcc3Yz14wZWwRZpd-_AFwjcAzK7NVWHXF-BYBHKSN_Kg-ecbOPF0hl2j5PzSK_r5w", "e": "AQAB", "d": "JZUJC-bS1rV96zekc4B4zyWnMWD2bYuZk2giCWSx5I3HO6FtSWCcmWZyQHN5oaaKrvGQibQxGqnzznLTnCcRoIQHrnIqPJcP1UhluzTb9H96Ia9PHRuQ0QhKBCqkZZeQ1c6EXizqpPRLnM8v1y1j1qcXpxZYOthHg4rbbI8RbhmNSxKkIVjDXguZ0oXkvUQ-BeAz3IWKu5eFdl11OVudwrGmk7noJO2dcr7gLxeyy6aLJ3BTSZ-M0VGcdzoWtYG6EA_y2JaMKBdNrTt1BzV6EpWRY-VpeT6AD_da2mM4eNsffnEnfgAmZWEHSejwYwYpodOZnyEs3g_lA4HdxB2ApQ", "p": "89Lii91meRmaBiU3gKiRap0W2UWgd9Jj1nULeYc18nl6dCYMhd-DPrCRqkNM1TU3Nfum2wBOyr6bavVkAQ2BrpH_bwETHLYV8b52f8OjNdoM46JCofZyjAcfJKDgfbSbN46NFRVIQVWEKJEhfwota-rfDyJH87Bw1OzCpdDAmes", "q": "9Ycky-aSfu9lrOtFdDY02XJ6WbFX5F6U0tXtBIUu6uzOjyiiIaV96GbwWMH5z0obmC4gwfLHJ3U4OywZYFwFcV9rbEnVKd7vmqNwiGXwpEBScwsreZHkr6BZhFtwXTQ4hqGGI15quCpuGcwZ-7F0e72YgPmaRwlGEeHYYY7AWvU"}'
  JWT_PUBLIC_SIGNING_JWK_SET: '{"keys": [{"kty": "RSA", "kid": "FEE4CI2B", "n": "6dmKES5VIa8BGU3CEpFU2qpd93jz5VySP2gTYmtjvpwP1TzrlzD2mys4Ia5b7WLSsZuhC0iPYD1oXclvYWW56qB-1rzAIXnqZo0q_9UB0cfxJzQknVK5AWA3Iu5hQLzEw4xPG46054KxiBIZaIhIVbl_HHMk1wVRy-v-3iRWN2yP-4nhsz9jRHAMqIaQTApXUFXTct3AZRbHBBffi9yJdIOYpp606HIMvbTCq6IzEi_WOFm7gCb1a3X4LtjagXFvASGfCiRjw7ZFBY5e9lEgoKcc3Yz14wZWwRZpd-_AFwjcAzK7NVWHXF-BYBHKSN_Kg-ecbOPF0hl2j5PzSK_r5w", "e": "AQAB"}]}'
  JWT_SIGNING_ALGORITHM: RS512
  JWT_SECRET_KEY: 'jwt_secret'
TIME_ZONE: 'UTC'