AWS_ACCESS_KEY_ID: acs98jmdf98ansxdf89asxf
AWS_SECRET_ACCESS_KEY: asiodfcnasd98fcuas8fcunadsf9c8asdfcasdoifxm89sdfx9a8
AWS_STORAGE_BUCKET_NAME: bucket
AWS_DEFAULT_ACL: 'public-read'
AWS_S3_REGION_NAME: ''
AWS_S3_ENDPOINT_URL: 'http://minio:9000'
ALLOWED_HOSTS:
  - '*'
BACKEND_SERVICE_EDX_OAUTH2_KEY: 'AnHf237Y0OWuNrurqT998pQh8QB4H4jY4OdG59Lk'
BACKEND_SERVICE_EDX_OAUTH2_SECRET:  'ETPIZ0X3GWCkVTdciRyhreb6omH7Ujkp0utGGxar3J9GHLeCTyzIiH9gqDnRscq6nQEa4hfPMfeFK57lib6lMTkWkJ8Y1MgggGgKk7Uhe8rxovtGqXAmmQFNbGUmt1cz'  # Local Development Values
BACKEND_SERVICE_EDX_OAUTH2_PROVIDER_URL: 'https://isa.andhael.cl/oauth2'
BACKEND_LMS_BASE_URL: 'https://isa.andhael.cl'
BACKEND_CMS_BASE_URL: 'https://studio.isa.andhael.cl'
BACKEND_ALLOWED_ROLES:
  - 'staff'
  - 'data researcher'
  - 'instructor'
  - 'administrator'
BACKEND_LOGS_DIR: '/app/logs'
CACHE:
  default:
    BACKEND: 'django_redis.cache.RedisCache'
    LOCATION: 'redis://@redis:6380/3'
    OPTIONS:
      CLIENT_CLASS: 'django_redis.client.DefaultClient'
      PASSWORD: 'msecret318e401514dd45e97daf49d1d5c36cdbf9a7294395e84a9f52c08c6ad3699fcc0'
    KEY_PREFIX: 'stats'
CELERY_BROKER_URL: 'redis://msecret318e401514dd45e97daf49d1d5c36cdbf9a7294395e84a9f52c08c6ad3699fcc0@redis:6380/2'
CELERY_BACKEND: 'redis://msecret318e401514dd45e97daf49d1d5c36cdbf9a7294395e84a9f52c08c6ad3699fcc0@redis:6380/2'
DJANGO_SECRET_KEY: 'lif-s82+7##n-lma+v@l_suzftkxy0%o&-ohnt6^^g_t9fu1bx'
DATABASES:
  default:
    ENGINE: 'django.db.backends.postgresql'
    NAME: 'postgres'
    USER: 'postgres'
    PASSWORD: 'postgres'
    HOST: 'db'
    PORT: 5432
  lms:
    ATOMIC_REQUESTS: true
    ENGINE: django.db.backends.mysql
    HOST: 172.16.244.52
    PORT: 3306
    NAME: 'edxapp'
    PASSWORD: 'edxapp_password'
    USER: 'edxapp'
EDX_DRF_EXTENSIONS:
  OAUTH2_USER_INFO_URL: "https://isa.andhael.cl/oauth2/user_info"
JWT_AUTH: 
  JWT_ALGORITHM: 'RS512'
  JWT_ISSUERS: 
    - AUDIENCE: 'set-me-please'
      ISSUER: 'issuer'
      SECRET_KEY: 'jwt_secret'
  JWT_VERIFY_AUDIENCE: False
  JWT_DECODE_HANDLER: 'edx_rest_framework_extensions.auth.jwt.decoder.jwt_decode_handler'
  JWT_AUTH_COOKIE: 'edx-jwt-cookie'
  JWT_PUBLIC_SIGNING_JWK_SET: '{"keys": [{"kty": "RSA", "kid": "FEE4CI2B", "n": "6dmKES5VIa8BGU3CEpFU2qpd93jz5VySP2gTYmtjvpwP1TzrlzD2mys4Ia5b7WLSsZuhC0iPYD1oXclvYWW56qB-1rzAIXnqZo0q_9UB0cfxJzQknVK5AWA3Iu5hQLzEw4xPG46054KxiBIZaIhIVbl_HHMk1wVRy-v-3iRWN2yP-4nhsz9jRHAMqIaQTApXUFXTct3AZRbHBBffi9yJdIOYpp606HIMvbTCq6IzEi_WOFm7gCb1a3X4LtjagXFvASGfCiRjw7ZFBY5e9lEgoKcc3Yz14wZWwRZpd-_AFwjcAzK7NVWHXF-BYBHKSN_Kg-ecbOPF0hl2j5PzSK_r5w", "e": "AQAB"}]}'
  JWT_AUTH_COOKIE_HEADER_PAYLOAD: 'edx-jwt-cookie-header-payload'
  JWT_AUTH_COOKIE_SIGNATURE: 'edx-jwt-cookie-signature'
  JWT_AUTH_HEADER_PREFIX: 'JWT'
TIME_ZONE: 'UTC'