AWS_ACCESS_KEY_ID: acs98jmdf98ansxdf89asxf
AWS_SECRET_ACCESS_KEY: asiodfcnasd98fcuas8fcunadsf9c8asdfcasdoifxm89sdfx9a8
AWS_STORAGE_BUCKET_NAME: bucket
AWS_DEFAULT_ACL: 'public-read'
AWS_S3_REGION_NAME: ''
AWS_S3_ENDPOINT_URL: 'http://minio:9000'
ALLOWED_HOSTS:
  - '*'
BACKEND_SERVICE_EDX_OAUTH2_KEY: 'g4S52ki5v1VjdozsLh0sgzoeovbunfqTz2pHZxOl'
BACKEND_SERVICE_EDX_OAUTH2_SECRET: 'ZLWeN0jegl0JxpwrSrgBvdNoP8X67HKKHJUi1rz2z49I4lQp6lPQQouYg9sDKp7D4dOnHyBxHccxmVdMBkHk877ZNGdx8CMDCVzuOxQlyrpLAtnFtn7EX5w9Lw1fXKZQ' # Local Development Values
BACKEND_SERVICE_EDX_OAUTH2_PROVIDER_URL: 'https://eol.andhael.cl/oauth2'
BACKEND_LMS_BASE_URL: 'https://eol.andhael.cl'
BACKEND_CMS_BASE_URL: 'https://cms.eol.andhael.cl'
BACKEND_ALLOWED_ROLES:
  - 'staff'
  - 'data researcher'
  - 'instructor'
  - 'administrator'
BACKEND_LOGS_DIR: '/app/logs'
CACHE:
  default:
    BACKEND: 'django_redis.cache.RedisCache'
    LOCATION: 'redis://@redis:6380/3'
    OPTIONS:
      CLIENT_CLASS: 'django_redis.client.DefaultClient'
      PASSWORD: 'msecret318e401514dd45e97daf49d1d5c36cdbf9a7294395e84a9f52c08c6ad3699fcc0'
    KEY_PREFIX: 'stats'
CELERY_BROKER_URL: 'redis://msecret318e401514dd45e97daf49d1d5c36cdbf9a7294395e84a9f52c08c6ad3699fcc0@redis:6380/2'
CELERY_BACKEND: 'redis://msecret318e401514dd45e97daf49d1d5c36cdbf9a7294395e84a9f52c08c6ad3699fcc0@redis:6380/2'
DJANGO_SECRET_KEY: 'lif-s82+7##n-lma+v@l_suzftkxy0%o&-ohnt6^^g_t9fu1bx'
DATABASES:
  default:
    ENGINE: 'django.db.backends.postgresql'
    NAME: 'postgres'
    USER: 'postgres'
    PASSWORD: 'postgres'
    HOST: 'db'
    PORT: 5432
EDX_DRF_EXTENSIONS:
  OAUTH2_USER_INFO_URL: 'https://eol.andhael.cl/oauth2/user_info'
JWT_AUTH:
  JWT_ALGORITHM: 'RS512'
  JWT_ISSUERS:
    - AUDIENCE: 'set-me-please'
      ISSUER: 'https://eol.andhael.cl/oauth2/'
      SECRET_KEY: 'jwt_secret'
  JWT_VERIFY_AUDIENCE: False
  JWT_DECODE_HANDLER: 'edx_rest_framework_extensions.auth.jwt.decoder.jwt_decode_handler'
  JWT_AUTH_COOKIE: 'edx-jwt-cookie'
  JWT_PUBLIC_SIGNING_JWK_SET: '{"keys": [{"kty": "RSA", "kid": "9YFYI3J6", "e": "AQAB", "n": "iZExe9pxsMO8n2R0N4YAcx7_e5ay3Z5ZMhQ1ok8hCp57SR1IX04MC5j0atVFX0a1GquXW65VasguMUzrMFvkpamkjeQ3CnIWQCyfFqqzfeO7e7x_sAcUcDbycRohKcXQVtEM_W-ObOi4-4KCf0bedsYfPMddTfgf-4buhzs2Qf0eim4PtD5d3AXO1q-P_i2kTbsq2VN8hWWFN4Dr0aIu8Jz7s4tZ0T57NfMQ6KcsDmVGMEucgoOvdWXN2g04yBkCBsnWUB-QZeGGgAslVsXvvizBWbkSSvwO6LHCYhsP0OfRZt-Qe5IF_Jd-FlH18coMLELfa3nL2ouYKffLakTiXQ"}]}'
  JWT_AUTH_COOKIE_HEADER_PAYLOAD: 'edx-jwt-cookie-header-payload'
  JWT_AUTH_COOKIE_SIGNATURE: 'edx-jwt-cookie-signature'
  JWT_AUTH_HEADER_PREFIX: 'JWT'
TIME_ZONE: 'UTC'
