# Generated by Django 2.2.16 on 2020-10-02 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVertical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.TextField()),
                ('course_name', models.TextField()),
                ('chapter', models.TextField()),
                ('chapter_name', models.TextField()),
                ('sequential', models.TextField()),
                ('sequential_name', models.TextField()),
                ('vertical', models.TextField()),
                ('vertical_name', models.TextField()),
                ('block_id', models.TextField()),
                ('vertical_number', models.IntegerField()),
                ('sequential_number', models.IntegerField()),
                ('chapter_number', models.IntegerField()),
                ('child_number', models.IntegerField()),
                ('block_type', models.TextField()),
                ('student_view_url', models.TextField()),
                ('lms_web_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('event_source', models.CharField(max_length=10)),
                ('name', models.TextField(blank=True, null=True)),
                ('accept_language', models.TextField()),
                ('ip', models.CharField(max_length=15)),
                ('agent', models.TextField()),
                ('page', models.TextField(blank=True, null=True)),
                ('host', models.CharField(max_length=30)),
                ('session', models.CharField(max_length=32)),
                ('referer', models.TextField()),
                ('time', models.DateTimeField()),
                ('event', models.TextField()),
                ('event_type', models.TextField()),
                ('course_id', models.TextField(blank=True)),
                ('org_id', models.CharField(blank=True, max_length=30)),
                ('user_id', models.IntegerField(blank=True)),
                ('path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffUserName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TimeOnPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type_vertical', models.TextField()),
                ('username', models.CharField(max_length=20)),
                ('session', models.IntegerField()),
                ('delta_time_float', models.FloatField()),
                ('course', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_processed_time_timestamp', models.DateTimeField(blank=True, null=True)),
                ('last_processed_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Courses.TimeOnPage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
