# Generated by Django 2.2.16 on 2020-10-14 21:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_auto_20201009_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeonpage',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 21, 6, 39, 566533, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staffusername',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='timeonpage',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
