# Generated by Django 2.2.16 on 2020-10-14 21:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_auto_20201014_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevertical',
            name='chapter_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coursevertical',
            name='course_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coursevertical',
            name='sequential_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coursevertical',
            name='vertical_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timeonpage',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 21, 16, 43, 567793, tzinfo=utc)),
        ),
    ]
