# Generated by Django 2.2.16 on 2020-10-28 13:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20201014_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('processed_on', models.DateTimeField(default=datetime.datetime(2020, 10, 28, 13, 0, 46, 879964, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='timeonpage',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 13, 0, 46, 879001, tzinfo=utc)),
        ),
    ]
