# Generated by Django 2.2.16 on 2020-10-28 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_auto_20201028_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfile',
            name='processed_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timeonpage',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
