# Generated by Django 2.2.16 on 2021-01-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevertical',
            name='block_type',
            field=models.CharField(max_length=100),
        ),
    ]
