# Generated by Django 2.2.16 on 2021-03-09 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210111_2011'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='log',
            index_together={('course_id', 'time')},
        ),
    ]
