# Generated by Django 2.2.16 on 2021-03-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210309_1953'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='log',
            index_together=set(),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['course_id', 'time'], name='core_log_course__ee2584_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['time'], name='core_log_time_6c4ee7_idx'),
        ),
    ]
