# Generated by Django 2.2.16 on 2021-05-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210309_2013'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='log',
            name='core_log_time_6c4ee7_idx',
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['id'], name='core_log_id_437d5c_idx'),
        ),
    ]
