# Generated by Django 2.2.16 on 2021-08-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210506_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevertical',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
