# Generated by Django 3.0.7 on 2021-11-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211022_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('date_joined', models.DateTimeField()),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('year_of_birth', models.CharField(blank=True, max_length=4, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
    ]
