# Generated by Django 3.0.7 on 2021-11-18 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
