"""
Django settings for Stats project.

Generated by 'django-admin startproject' using Django 2.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'lif-s82+7##n-lma+v@l_suzftkxy0%o&-ohnt6^^g_t9fu1bx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', False)

ALLOWED_HOSTS = ['*', ""]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'Courses',
    'django_celery_results',
    'django_celery_beat',
    'django_filters',
    'crispy_forms',
    'csrf.apps.CsrfAppConfig',  # Enables frontend apps to retrieve CSRF tokens.
    'social_django',
]

MIDDLEWARE = [
    'edx_django_utils.cache.middleware.RequestCacheMiddleware',
    'edx_rest_framework_extensions.auth.jwt.middleware.JwtRedirectToLoginIfUnauthenticatedMiddleware',
    'edx_rest_framework_extensions.auth.jwt.middleware.JwtAuthCookieMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'edx_rest_framework_extensions.middleware.RequestMetricsMiddleware',
    'edx_rest_framework_extensions.auth.jwt.middleware.EnsureJWTAuthSettingsMiddleware',
    'edx_django_utils.cache.middleware.TieredCacheMiddleware',
]

ROOT_URLCONF = 'Stats.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Stats.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'db',
        'PORT': 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES' : [
        'edx_rest_framework_extensions.permissions.LoginRedirectIfUnauthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'edx_rest_framework_extensions.auth.jwt.authentication.JwtAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 25,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}

CELERY_BROKER_URL = "redis://msecret318e401514dd45e97daf49d1d5c36cdbf9a7294395e84a9f52c08c6ad3699fcc0@redis:6380/2"
CELERY_BACKEND = "redis://msecret318e401514dd45e97daf49d1d5c36cdbf9a7294395e84a9f52c08c6ad3699fcc0@redis:6380/2"

# Oauth JWT Token verification config
JWT_AUTH = {
    'JWT_ALGORITHM': 'RS512',
    'JWT_AUDIENCE': None,
    'JWT_ISSUER': 'issuer',
    'JWT_ISSUERS': [{
        'AUDIENCE': 'set-me-please',
        'ISSUER': 'issuer',
        'SECRET_KEY': 'jwt_secret'
    }],
    'JWT_VERIFY_AUDIENCE': False,
    'JWT_SECRET_KEY': 'jwt_secret',
    'JWT_DECODE_HANDLER': 'edx_rest_framework_extensions.auth.jwt.decoder.jwt_decode_handler',
    'JWT_AUTH_COOKIE': 'edx-jwt-cookie',
    'JWT_PUBLIC_SIGNING_JWK_SET': '{"keys": [{"kty": "RSA", "kid": "9YFYI3J6", "e": "AQAB", "n": "iZExe9pxsMO8n2R0N4YAcx7_e5ay3Z5ZMhQ1ok8hCp57SR1IX04MC5j0atVFX0a1GquXW65VasguMUzrMFvkpamkjeQ3CnIWQCyfFqqzfeO7e7x_sAcUcDbycRohKcXQVtEM_W-ObOi4-4KCf0bedsYfPMddTfgf-4buhzs2Qf0eim4PtD5d3AXO1q-P_i2kTbsq2VN8hWWFN4Dr0aIu8Jz7s4tZ0T57NfMQ6KcsDmVGMEucgoOvdWXN2g04yBkCBsnWUB-QZeGGgAslVsXvvizBWbkSSvwO6LHCYhsP0OfRZt-Qe5IF_Jd-FlH18coMLELfa3nL2ouYKffLakTiXQ"}]}',
    'JWT_AUTH_COOKIE_HEADER_PAYLOAD': 'edx-jwt-cookie-header-payload',
    'JWT_AUTH_COOKIE_SIGNATURE': 'edx-jwt-cookie-signature',
    'JWT_AUTH_HEADER_PREFIX': 'JWT',
}

EDX_DRF_EXTENSIONS = {
    "OAUTH2_USER_INFO_URL": "https://eol.andhael.cl/oauth2/user_info",
    "JWT_PAYLOAD_USER_ATTRIBUTES": {
        'administrator': 'is_staff',
        'email': 'email',
    },
    'ENABLE_SET_REQUEST_USER_FOR_JWT_COOKIE': True,
}

# Custom settings
BACKEND_SERVICE_EDX_OAUTH2_KEY = 'g4S52ki5v1VjdozsLh0sgzoeovbunfqTz2pHZxOl' # Local Development Values
BACKEND_SERVICE_EDX_OAUTH2_SECRET = 'ZLWeN0jegl0JxpwrSrgBvdNoP8X67HKKHJUi1rz2z49I4lQp6lPQQouYg9sDKp7D4dOnHyBxHccxmVdMBkHk877ZNGdx8CMDCVzuOxQlyrpLAtnFtn7EX5w9Lw1fXKZQ' # Local Development Values
BACKEND_SERVICE_EDX_OAUTH2_PROVIDER_URL = 'https://eol.andhael.cl/oauth2'
BACKEND_LMS_BASE_URL = 'https://eol.andhael.cl'
BACKEND_ALLOWED_ROLES = [
    'staff',
    'data researcher',
    'instructor',
    'administrator'
]
# Should be an absolute path
BACKEND_LOGS_DIR = '/app/logs'

# EDX OAUTH2 
SOCIAL_AUTH_EDX_OAUTH2_KEY = 'g4S52ki5v1VjdozsLh0sgzoeovbunfqTz2pHZxOl'
SOCIAL_AUTH_EDX_OAUTH2_SECRET = 'ZLWeN0jegl0JxpwrSrgBvdNoP8X67HKKHJUi1rz2z49I4lQp6lPQQouYg9sDKp7D4dOnHyBxHccxmVdMBkHk877ZNGdx8CMDCVzuOxQlyrpLAtnFtn7EX5w9Lw1fXKZQ'
SOCIAL_AUTH_EDX_OAUTH2_URL_ROOT = 'https://eol.andhael.cl'
SOCIAL_AUTH_EDX_OAUTH2_PUBLIC_URL_ROOT = 'https://eol.andhael.cl'
SOCIAL_AUTH_EDX_OAUTH2_JWS_HMAC_SIGNING_KEY = 'jwt_secret'
# SOCIAL_AUTH_EDX_OAUTH2_PROVIDER_CONFIGURATION_CACHE_TTL use default 1 Week 
# SOCIAL_AUTH_EDX_OAUTH2_JWKS_CACHE_TTL use default 1 day.
SOCIAL_AUTH_STRATEGY = 'auth_backends.strategies.EdxDjangoStrategy'

AUTHENTICATION_BACKENDS = (
    'auth_backends.backends.EdXOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

LOGIN_REDIRECT_URL = '/'