# Generated by Django 2.2.16 on 2020-10-29 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOnPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type_vertical', models.TextField()),
                ('sequential', models.TextField(blank=True)),
                ('username', models.CharField(max_length=150)),
                ('session', models.IntegerField()),
                ('delta_time_float', models.FloatField()),
                ('course', models.TextField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
