# Generated by Django 2.2.16 on 2021-08-11 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_coursevertical_is_active'),
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeonpage',
            name='course',
        ),
        migrations.RemoveField(
            model_name='timeonpage',
            name='event_type_vertical',
        ),
        migrations.RemoveField(
            model_name='timeonpage',
            name='sequential',
        ),
        migrations.AddField(
            model_name='timeonpage',
            name='vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CourseVertical'),
        ),
    ]
